kind: Service
apiVersion: v1
metadata:
  name: front
  namespace: phonebook-app
spec:
  selector:
    app: front-app
    env: demo
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
  type: LoadBalancer
